# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20170501_1512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Individual',
        ),
    ]
