# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20170501_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='job_post',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
