# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20170426_0421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='area_of_interest',
        ),
    ]
