# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_company_job_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='job_post',
            field=models.CharField(default='', max_length=200),
        ),
    ]
