# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_profile_area_of_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
